### ISSUE TITLE
Bump to HDP 2.6.1

### ISSUE THREAD

**Issue by dongjoon-hyun** [hortonworks-spark/spark-llap#135]

**Comment by dongjoon-hyun** [comment]
Hi, @merlintang . Please use this issue when you bump up.

**Comment by merlintang** [comment]
got it.

**Comment by merlintang** [comment]
so, we also need to bump the vision number to v1.0.6-1.6 and v1.1.3-2.1 for
spark 1.6 and 2.1, respectively.
I will bump the branch 1.6 once the desc table function is merged.

**Comment by dongjoon-hyun** [comment]
Okay, then, let's split the work item. I will proceed `master` and `branch-2.1` first.
You can do `branch-1.6` and `branch-2.2` later.

**Comment by merlintang** [comment]
thanks Dongjoon.
