### ISSUE TITLE
Change JDBCWrapper.resolveQuery() to use LIMIT 0 rather than 1=0 for faster 0-row result

### ISSUE THREAD

**Issue by jdere** [hortonworks-spark/spark-llap#169]
The SQL query used during LlapRelation.schema can sometimes result in running the entire query. Change the SQL to use LIMIT 0 rather than 1=0 .. this still returns a 0-row result, but Hive knows to optimize LIMIT 0 so that it does not actually run the query, but still returns the resulting schema.

**Comment by merlintang** [comment]
This patch is committed. close this.
