### ISSUE TITLE
I can't find spark-llap-2.0.0.2.5.3.0-37-assembly.jar

### ISSUE THREAD

**Issue by xijian** [hortonworks-spark/spark-llap#239]
spark：2.0.0
HDP：2.5.3

I can't find spark-llap-2.0.0.2.5.3.0-37-assembly.jar

please help me！

**Comment by jdere** [comment]
Take a look at https://github.com/hortonworks-spark/spark-llap/issues/9, might be helpful.

**Comment by xijian** [comment]
Thank you！ I can find spark-llap-1.0.0.2.5.3.0-37-assembly.jar in #9 ，but  it not work for spark2
